import BottomBar from "@/components/shared/bottom-bar";
import type { Metadata } from "next";
import dynamic from "next/dynamic";

const TopBar = dynamic(() => import("@/components/shared/top-bar"), {
  ssr: false,
});

const ModalsWrapper = dynamic(() => import("@/components/modals-wrapper"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "threelingo | Learn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section id="learn-layout" className="relative">
      <TopBar />
      <BottomBar />
      {children}
      <ModalsWrapper />
    </section>
  );
  // return (
  //   <div className="grid grid-cols-1 md:grid-cols-4 lg:grid-cols-6 bg-background text-foreground relative">
  //     <LeftSidebar />
  //     <div className="col-span-1 md:col-span-3 lg:col-span-5">
  //       <LearnWrapper>{children}</LearnWrapper>
  //     </div>
  //     {/* <RightSidebar /> */}
  //   </div>
  // );
}
